### ISSUE TITLE
Preprocessing might not be compatible with curate_npr after  update to 0.2.9 (?)

### ISSUE THREAD

**Issue by idaElken** [psychgen/phenotools#2]
Hi,
I updated to 0.2.9 on p697. 

We use preload_npr for preprocessing but now it seems the variables of the preprocessing files are not recognized by curate_npr:
<img width="904" alt="Screenshot 2022-10-26 at 09 36 29" src="https://user-images.githubusercontent.com/4227962/197965095-b35d499a-3831-49e1-a5e0-de6bcf2a4003.png">

Any advice?

Best, 
Ida

**Comment by idaElken** [comment]
Command used for preload_npr:
<img width="834" alt="Screenshot 2022-10-26 at 09 56 55" src="https://user-images.githubusercontent.com/4227962/197968162-7ed7014f-a6c1-489b-93d9-a987afe03afb.png">

Column-names of output of preload_npr (in case this is helpful):
<img width="936" alt="Screenshot 2022-10-26 at 09 56 31" src="https://user-images.githubusercontent.com/4227962/197968336-c4c630d1-8d91-449d-8681-7de4bb2eee12.png">

**Comment by idaElken** [comment]
I could partially circumvent by doing:
preprocd_npr$BARN_NR <- preprocd_npr$LNr2
preprocd_npr$LNr <- preprocd_npr$LNr2

Thus, it is probably related to this coding in curate_npr (?): 
if(any(!c("preg_id", "BARN_NR", "m_id","f_id","FAAR", "dx_owner","LNr")
           %in% names(npr_preprocessed))){
      stop("Pre-processed NPR file is missing key variables, or they are not named
      in a way that phenotools can recognise. Check ?curate_npr for the very
      specific criteria that must apply to preprocessed NPR data.")
    }

However, when running with the updated preprocessed files, then I run into this issue:
<img width="819" alt="Screenshot 2022-10-26 at 10 12 45" src="https://user-images.githubusercontent.com/4227962/197971656-c855ef04-d352-41aa-ab9e-86d53149ce90.png">

**Comment by idaElken** [comment]
And another addition: 
Tried:
preprocd_npr$LNr1 <- NULL
preprocd_npr$LNr2 <- NULL

Runs for a while but exits with this error: 
<img width="833" alt="Screenshot 2022-10-26 at 12 23 11" src="https://user-images.githubusercontent.com/4227962/198002517-2f4d97c1-8037-4b4d-af51-b279f3a57bfd.png">

**Comment by lauriejh** [comment]
This is a bit strange. Do you know if preload_npr was always giving LNr1 and LNr2- prior to the update? Are these variables identical or not? There should only be one LNr column.

I will double-check this works in p471 and then come on to p697 to have a look. I think the issue will likely be because of some feature of the p697 dataset that Nora and I created that I had forgotten about in this update. Probably, the fix will involve amending that dataset rather than phenotools code - but I will add more detailed information to the requirements for the structure of preprocessed files to avoid this in future. The difficulty comes from there being slight differences in the way data look when delivered to different projects.

By the way, you won't have made it there yet because of this issue, but as soon as I saw your name I realised I had managed, in this update, simultaneously to fail to add your extra diagnoses _and_ close off the loophole that you were using to put them in manually... Sorry about that! Can you send me your formatted list again by email and I will provide a patched version for you? Eventually all ICD-10 codes will be in but I haven't got to that yet.

**Comment by lauriejh** [comment]
Sorry: forget this last bit. I found what you sent last time.

**Comment by idaElken** [comment]
Hey, 

Just checked with Samuel who is running his analysis with version 0.2.7. This preload_npr version only gives out LNr (thus NOT neither LNr1 or LNr2). I have not looked enough at the code to figure out why that is. Let me know if there is something else I need to check up, e.g. sending you the column-header or something. 

Wrt diagnoses - I think for other projects (ours included), it would be help if one could define/add diagnoses oneself (if possible). Then, in case we received additional diagnoses from NPR (or I added 'too many' diagnoses because of misunderstandings), we could add them ourselves (?). I suppose some projects would not have F-diagnoses at all but other diagnoses-codes would be relevant (?)

**Comment by lauriejh** [comment]
@idaElken hoping to get a patched version out today resolving both of these issues. Will close this and let you know if so, but obviously re-open if it doesn't solve or if you run in to downstream issues.

**Comment by lauriejh** [comment]
[phenotools_0.2.9.9999.zip](https://github.com/psychgen/phenotools/files/9922515/phenotools_0.2.9.9999.zip)

Please try 0.2.9.9999 which should resolve both of these issues. Uploaded to p697-member-group (or attached here in case you can't find it). The update includes all theoretically available ICD-10 codes, but removes your ability to add your own as you did in 0.2.7. See how you go and if you are getting substantially different numbers, or if the codes you need are somehow not available, let me know and I'll see if I can build in the possibility of user customizable code lists in the next version.

**Comment by idaElken** [comment]
Hey. Not a reopening - just wanted to give positive feedback on 0.2.9.9999:
- preload_npr works like a charm.  
- extracting other ICD-10 codes than F works as well and gives same numbers for the few (I50 & I1) that I tested out.
Well done!
